export {default as Navbar} from './Navbar'
export {default as Hero} from './Hero'
export {default as Footer} from './Footer'
export {default as Section1} from './Section1'
export {default as Section2} from './Section2'